/*
 * Chatbot messages are contained in a JTextArea and JScrollPane for ease of use. 
 * This may be changed later
 * 
 * 
 */

import java.awt.Color;
import java.awt.Font;
import java.awt.event.AdjustmentEvent;
import java.awt.event.AdjustmentListener;

public class GUI extends javax.swing.JFrame {
	
	private static final long serialVersionUID = 1L;
	public static javax.swing.JTextArea ChatLog;
	private javax.swing.JScrollPane jScrollPane1;
	Font textFont = new Font("SAO UI", Font.PLAIN, 12);
	
    /** Creates new form GUI */
    public GUI() {
        initComponents();
        this.setTitle("Botthecatman");
    }
 
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    public void initComponents() {
 
        jScrollPane1 = new javax.swing.JScrollPane();
        ChatLog = new javax.swing.JTextArea();
 
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
 
        ChatLog.setBackground(Color.DARK_GRAY);
        ChatLog.setColumns(5);        
        ChatLog.setRows(15);
        ChatLog.setFont(textFont);
        ChatLog.setForeground(Color.WHITE);
        ChatLog.setEditable(false);
        ChatLog.append("\n");
        
        jScrollPane1.setViewportView(ChatLog);
        jScrollPane1.getVerticalScrollBar().addAdjustmentListener(new AdjustmentListener() 
        {
        	public void adjustmentValueChanged(AdjustmentEvent e) {
        		e.getAdjustable().setValue(e.getAdjustable().getMaximum());  
            }
        }); 
                
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        getContentPane().setBackground(Color.DARK_GRAY);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) 
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
                .addContainerGap(20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addGap(20, 20, 20)
                .addContainerGap())
        );
        pack();
    }
 
    /**
    * Starts the GUI components of this bot
    */
    public void ShowComponents() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
}